name: BedrockClans
main: Wertzui123\BedrockClans\Main
version: 3.7
api: 4.0.0
load: POSTWORLD
author: Wertzui123
description: An advanced PocketMine-MP clan plugin with many creative features
website: https://github.com/Wertzui123/BedrockClans
permissions:
  bedrockclans.command.join:
    default: op
    description: Allows you to use /clan join
  bedrockclans.command.create:
    default: op
    description: Allows you to create clans
  bedrockclans.create.cost.bypass:
    default: false
    description: Allows you to bypass the clan creation cost