name: BedrockClans
main: Wertzui123\BedrockClans\Main
version: 3.1
api: 3.0.0
load: POSTWORLD
author: Wertzui123
description: A PocketMine-MP clan plugin with many cool features
website: https://github.com/Wertzui123/BedrockClans
permissions:
  bedrockclans:
    default: op
    description: Lets you use a BedrockClans features
    children:
      bedrockclans.command.join:
        default: op
        description: Allows you to use /clan join
      bedrockclans.command.create:
        default: op
        description: Allows you to create clans
      bedrockclans.create.cost.bypass:
        default: false
        description: Allows you to bypass the clan creation cost